[package]
name = "fast-statistics"
version = "0.1.0"
authors = ["risboo6909 <ttyv00@gmail.com>"]

[dependencies]
rayon = "1.0"
rand = "0.4"

[dev-dependencies]
quickcheck = "0.6"

[dependencies.pyo3]
version = "0.2"
features = ["extension-module", "python2"]

[lib]
name = "fast_stat"
crate-type = ["cdylib"]

[profile.release]
debug = false
opt-level = 3
